# DATABASE (PostgreSQL - Neon)
spring.datasource.url=jdbc:postgresql://localhost:5432/SiddhiVinayak_DB
spring.datasource.username=postgres
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# MAIL (Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=shantanukumbhar310@gmail.com
spring.mail.password=vjxv altu swar otcg
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.thymeleaf.cache=false

# CLOUDINARY
cloudinary.url=cloudinary://871626453924828:we-kLLF_mAzIgKP6IWXuQd5V5cU@devzgyotn

# SERVER
server.port=${PORT:8080}
server.tomcat.max-part-count=500


jwt.secret=9a4f2c8d3e1b7a6c5f8e3d2a1b4c7f9e8d5b2a6c3f7e9d1b5c8a2f4e7d9b1c3
jwt.expiration=86400000

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
