# Database Configuration - MUST start with jdbc:postgresql://
#spring.datasource.url=jdbc:postgresql://ep-silent-leaf-aosufnal-pooler.c-2.ap-southeast-1.aws.neon.tech:5432/neondb?sslmode=require
#spring.datasource.username=neondb_owner
#spring.datasource.password=npg_S2ZeAawdO7Cr
#spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.url=jdbc:postgresql://localhost:5432/SiddhiVinayak_DB
spring.datasource.username=postgres
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver
app.base-url=https://siddhivinayak-arts.onrender.com

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false

# Mail (Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=shantanukumbhar310@gmail.com
spring.mail.password=vjxv altu swar otcg
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Thymeleaf
spring.thymeleaf.cache=false

# Cloudinary
cloudinary.url=cloudinary://544913587722279:we-kLLF_mAzIgKP6IWXuQd5V5cUaDevzgyotn

# Server
server.port=8080
server.tomcat.max-part-count=500

# Admin
admin.whatsapp.number=918767739911

# JWT
jwt.secret=9a4f2c8d3e1b7a6c5f8e3d2a1b4c7f9e8d5b2a6c3f7e9d1b5c8a2f4e7d9b1c3

# Multipart
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB